apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: metronome-dha-qa-09162023
    meta.helm.sh/release-namespace: metronome-qa
  creationTimestamp: "2024-09-04T21:34:08Z"
  labels:
    app: metronome-master
    app.kubernetes.io/managed-by: Helm
    chart: elasticsearch
    heritage: Helm
    release: metronome-dha-qa-09162023
  name: metronome-master
  namespace: metronome-qa
  resourceVersion: "166820590"
  uid: 4fbc21e3-c644-40ed-b029-aeb4c8a9acb6
spec:
  clusterIP: 10.100.70.91
  clusterIPs:
  - 10.100.70.91
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 9200
    protocol: TCP
    targetPort: 9200
  - name: transport
    port: 9300
    protocol: TCP
    targetPort: 9300
  selector:
    app: metronome-master
    chart: elasticsearch
    release: metronome-dha-qa-09162023
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
