apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: metronome-dha-qa-09162023
    meta.helm.sh/release-namespace: metronome-qa
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  creationTimestamp: "2024-09-04T21:34:08Z"
  labels:
    app: metronome-master
    app.kubernetes.io/managed-by: Helm
    chart: elasticsearch
    heritage: Helm
    release: metronome-dha-qa-09162023
  name: metronome-master-headless
  namespace: metronome-qa
  resourceVersion: "166820587"
  uid: ba844def-e958-420f-bd19-c06c8c4879ef
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 9200
    protocol: TCP
    targetPort: 9200
  - name: transport
    port: 9300
    protocol: TCP
    targetPort: 9300
  publishNotReadyAddresses: true
  selector:
    app: metronome-master
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
