apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: metronome-dha-qa-09162023
    meta.helm.sh/release-namespace: metronome-qa
  creationTimestamp: "2024-10-02T21:54:53Z"
  labels:
    app.kubernetes.io/instance: metronome-dha-qa-09162023
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: cassandra
    helm.sh/chart: cassandra-9.2.3
  name: metronome-dha-qa-09162023-cassandra
  namespace: metronome-qa
  resourceVersion: "176700781"
  uid: 684a2a78-fffa-4869-b5eb-d5b484bcbdfa
spec:
  clusterIP: 10.100.137.8
  clusterIPs:
  - 10.100.137.8
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: cql
    port: 9042
    protocol: TCP
    targetPort: cql
  - name: metrics
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: metronome-dha-qa-09162023
    app.kubernetes.io/name: cassandra
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
