apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-10-02T21:54:53Z"
  generateName: metronome-dha-qa-09162023-746c6f8455-
  labels:
    app.kubernetes.io/instance: metronome-dha-qa-09162023
    app.kubernetes.io/name: metronome
    pod-template-hash: 746c6f8455
  name: metronome-dha-qa-09162023-746c6f8455-mlw7z
  namespace: metronome-qa
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: metronome-dha-qa-09162023-746c6f8455
    uid: d2dca097-4789-4296-80df-20163cd93441
  resourceVersion: "176701066"
  uid: 9a024064-0a92-4d58-aed8-c1a47c91985f
spec:
  containers:
  - env:
    - name: METRONOME_DB_HOST
      value: metronome-dha-qa-09162023-cassandra.metronome-qa.svc.cluster.local
    - name: METRONOME_ES_HOST
      value: metronome-master.metronome-qa.svc.cluster.local
    - name: METRONOME_WEB_HOST
      value: metronome-dha-qa-09162023-metronome.metronome-qa.svc.cluster.local
    - name: METRONOME_DAS_URL
      value: https://metronome-dha.radustech.io:8082
    - name: METRONOME_INT_DAS_URL
      value: http://localhost:8082
    - name: METRONOME_APP_URL
      value: https://metronome-dha.radustech.io:8083
    - name: METRONOME_INT_APP_URL
      value: http://localhost:8083
    - name: METRONOME_EVAL_URL
      value: https://metronome-dha.radustech.io:3000
    - name: METRONOME_INT_EVAL_URL
      value: http://localhost:3000
    - name: METRONOME_WEB_URL
      value: https://metronome-dha.radustech.io
    - name: METRONOME_RESOURCE_URL
      value: https://metronome-dha.radustech.io/
    - name: METRONOME_RESOURCE_DEV_URL
      value: https://metronome-dha.radustech.io/
    - name: METRONOME_COOKIE_DOMAIN
      value: metronome-dha.radustech.io
    - name: METRONOME_VIRTUAL_HOST
      value: metronome-dha.radustech.io
    - name: METRONOME_DB_USER
      value: cassandra
    - name: METRONOME_DB_PASS
      value: tnc{SJH<Ba@46k=yDD
    - name: METRONOME_EMAIL_HOST
      value: smtp.gmail.com
    - name: METRONOME_EMAIL_PORT
      value: "465"
    - name: METRONOME_EMAIL_SECURE
      value: "true"
    - name: METRONOME_EMAIL_USER
    - name: METRONOME_EMAIL_PASS
    - name: METRONOME_EMAIL_FROM
    - name: METRONOME_AUTH_PROVIDER
      value: keycloak
    - name: METRONOME_AUTH_PROVIDER_URL
      value: https://auth1.radustech.io/auth
    - name: METRONOME_AUTH_PROVIDER_REALM
      value: metronome
    - name: METRONOME_AUTH_PROVIDER_CLIENT_ID
      value: metronomedha
    - name: METRONOME_AUTH_PROVIDER_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          key: METRONOME_AUTH_PROVIDER_CLIENT_SECRET
          name: rhsso-client-secret
    image: 147376904629.dkr.ecr.us-gov-east-1.amazonaws.com/metronome:1.2.4.2
    imagePullPolicy: Always
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /resource/index.html
        port: http
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    name: metronome
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /resource/index.html
        port: http
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      limits:
        cpu: "2"
        memory: 12Gi
      requests:
        cpu: "1"
        memory: 12Gi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        add:
        - NET_BIND_SERVICE
      privileged: false
      runAsGroup: 1001
      runAsNonRoot: true
      runAsUser: 1000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-ndn8d
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: aws-erc
  nodeName: ip-192-168-155-12.us-gov-east-1.compute.internal
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: metronome-dha-qa-09162023
  serviceAccountName: metronome-dha-qa-09162023
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-ndn8d
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-10-02T21:54:53Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-10-02T21:55:32Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-10-02T21:55:32Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-10-02T21:54:53Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://c8e8e790435b282186fbf867c84ed031c7050ca52005d773ce58fc1273f7f001
    image: 147376904629.dkr.ecr.us-gov-east-1.amazonaws.com/metronome:1.2.4.2
    imageID: 147376904629.dkr.ecr.us-gov-east-1.amazonaws.com/metronome@sha256:f0230e3417380138bc3726182460892ea0585cb00cb219afcaeb7af03b582016
    lastState: {}
    name: metronome
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-10-02T21:55:31Z"
  hostIP: 192.168.155.12
  phase: Running
  podIP: 192.168.153.111
  podIPs:
  - ip: 192.168.153.111
  qosClass: Burstable
  startTime: "2024-10-02T21:54:53Z"
