apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: metronome-dha-qa-09162023
    meta.helm.sh/release-namespace: metronome-qa
  creationTimestamp: "2025-05-13T21:17:07Z"
  labels:
    app.kubernetes.io/instance: metronome-dha-qa-09162023
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: metronome
    app.kubernetes.io/version: 1.2.7
    helm.sh/chart: metronome-1.2.7
  name: metronome-discovery
  namespace: metronome-qa
  resourceVersion: "255353243"
  uid: e09d20ef-35fc-4483-aed6-ab273c9cdfb9
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: metronome-discovery-web-das
    port: 5701
    protocol: TCP
    targetPort: 5701
  - name: metronome-discovery-web-eval
    port: 5702
    protocol: TCP
    targetPort: 5702
  selector:
    app.kubernetes.io/instance: metronome-dha-qa-09162023
    app.kubernetes.io/name: metronome
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
