apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-10-02T21:54:53Z"
  generateName: metronome-dha-qa-09162023-cassandra-
  labels:
    app.kubernetes.io/instance: metronome-dha-qa-09162023
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: cassandra
    controller-revision-hash: metronome-dha-qa-09162023-cassandra-796bb9b996
    helm.sh/chart: cassandra-9.2.3
    statefulset.kubernetes.io/pod-name: metronome-dha-qa-09162023-cassandra-0
  name: metronome-dha-qa-09162023-cassandra-0
  namespace: metronome-qa
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: StatefulSet
    name: metronome-dha-qa-09162023-cassandra
    uid: 9e19780c-4b97-4205-8c52-1d81f99fada8
  resourceVersion: "176701212"
  uid: 1e69a3f8-7db2-4e7a-9df2-4b1bcd27ada7
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchLabels:
              app.kubernetes.io/instance: metronome-dha-qa-09162023
              app.kubernetes.io/name: cassandra
          namespaces:
          - metronome-qa
          topologyKey: kubernetes.io/hostname
        weight: 1
  containers:
  - command:
    - bash
    - -ec
    - |
      # Node 0 is the password seeder
      if [[ $POD_NAME =~ (.*)-0$ ]]; then
          echo "Setting node as password seeder"
          export CASSANDRA_PASSWORD_SEEDER=yes
      else
          # Only node 0 will execute the startup initdb scripts
          export CASSANDRA_IGNORE_INITDB_SCRIPTS=1
      fi
      /opt/bitnami/scripts/cassandra/entrypoint.sh /opt/bitnami/scripts/cassandra/run.sh
    env:
    - name: BITNAMI_DEBUG
      value: "false"
    - name: CASSANDRA_CLUSTER_NAME
      value: metronome
    - name: CASSANDRA_SEEDS
      value: metronome-dha-qa-09162023-cassandra-0.metronome-dha-qa-09162023-cassandra-headless.metronome-qa.svc.cluster.local
    - name: CASSANDRA_PASSWORD
      valueFrom:
        secretKeyRef:
          key: cassandra-password
          name: metronome-dha-qa-09162023-cassandra
    - name: POD_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: CASSANDRA_USER
      value: cassandra
    - name: CASSANDRA_NUM_TOKENS
      value: "256"
    - name: CASSANDRA_DATACENTER
      value: dc1
    - name: CASSANDRA_ENDPOINT_SNITCH
      value: SimpleSnitch
    - name: CASSANDRA_KEYSTORE_LOCATION
      value: /opt/bitnami/cassandra/certs/keystore
    - name: CASSANDRA_TRUSTSTORE_LOCATION
      value: /opt/bitnami/cassandra/certs/truststore
    - name: CASSANDRA_RACK
      value: rack1
    - name: MAX_HEAP_SIZE
      value: 4g
    - name: HEAP_NEWSIZE
      value: 800m
    - name: CASSANDRA_TRANSPORT_PORT_NUMBER
      value: "7000"
    - name: CASSANDRA_JMX_PORT_NUMBER
      value: "7199"
    - name: CASSANDRA_CQL_PORT_NUMBER
      value: "9042"
    image: 147376904629.dkr.ecr.us-gov-east-1.amazonaws.com/metronome-cassandra:1.2.3.7
    imagePullPolicy: Always
    livenessProbe:
      exec:
        command:
        - /bin/bash
        - -ec
        - |
          nodetool status
      failureThreshold: 5
      initialDelaySeconds: 60
      periodSeconds: 30
      successThreshold: 1
      timeoutSeconds: 30
    name: cassandra
    ports:
    - containerPort: 7000
      name: intra
      protocol: TCP
    - containerPort: 7001
      name: tls
      protocol: TCP
    - containerPort: 7199
      name: jmx
      protocol: TCP
    - containerPort: 9042
      name: cql
      protocol: TCP
    readinessProbe:
      exec:
        command:
        - /bin/bash
        - -ec
        - |
          nodetool status | grep -E "^UN\\s+${POD_IP}"
      failureThreshold: 5
      initialDelaySeconds: 60
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 30
    resources: {}
    securityContext:
      runAsNonRoot: true
      runAsUser: 1001
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /bitnami/cassandra
      name: data
    - mountPath: /docker-entrypoint-initdb.d/configmap
      name: init-db-cm
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-kw47s
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostname: metronome-dha-qa-09162023-cassandra-0
  nodeName: ip-192-168-182-149.us-gov-east-1.compute.internal
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1001
  serviceAccount: metronome-dha-qa-09162023-cassandra
  serviceAccountName: metronome-dha-qa-09162023-cassandra
  subdomain: metronome-dha-qa-09162023-cassandra-headless
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: data-metronome-dha-qa-09162023-cassandra-0
  - configMap:
      defaultMode: 420
      name: init-db
    name: init-db-cm
  - name: kube-api-access-kw47s
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-10-02T21:54:53Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-10-02T21:56:04Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-10-02T21:56:04Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-10-02T21:54:53Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://d4bb1101b2f611bfb6cbcc362aed88686ee05a2997061e593053ad28d09a6fd0
    image: 147376904629.dkr.ecr.us-gov-east-1.amazonaws.com/metronome-cassandra:1.2.3.7
    imageID: 147376904629.dkr.ecr.us-gov-east-1.amazonaws.com/metronome-cassandra@sha256:c270c975f2a523e20c78aead532d98364c35e65ea1d9b1657f0c9548cfd879ff
    lastState: {}
    name: cassandra
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-10-02T21:55:01Z"
  hostIP: 192.168.182.149
  phase: Running
  podIP: 192.168.176.162
  podIPs:
  - ip: 192.168.176.162
  qosClass: BestEffort
  startTime: "2024-10-02T21:54:53Z"
